// export const LOGIN_SUCCES = 'LOGIN_SUCCESS';
// export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const AuthType = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  EMAIL_CHANGE: 'EMAIL_CHANGE',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
};
